# -*- coding: utf-8 -*-
"""Ejercicio 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TE40drQ5XbYrS27vFBGS_2fH5SfhcbW5
"""

def sumar(a, b):
    return a + b

def restar(a, b):
    return a - b

def multiplicar(a, b):
    return a * b

def dividir(a, b):
    if b == 0:
        return "Error: No se puede dividir por cero"
    else:
        return a / b

def mostrar_menu():
    print("Operaciones disponibles:")
    print("1. Sumar")
    print("2. Restar")
    print("3. Multiplicar")
    print("4. Dividir")
    print("5. Salir")

def calculadora():
    while True:
        mostrar_menu()
        try:
            opcion = int(input("Elige una opción (1/2/3/4/5): "))

            if opcion == 5:
                print("¡Adiós!")
                break

            num1 = float(input("Introduce el primer número: "))
            num2 = float(input("Introduce el segundo número: "))

            if opcion == 1:
                print(f"{num1} + {num2} = {sumar(num1, num2)}")
            elif opcion == 2:
                print(f"{num1} - {num2} = {restar(num1, num2)}")
            elif opcion == 3:
                print(f"{num1} * {num2} = {multiplicar(num1, num2)}")
            elif opcion == 4:
                print(f"{num1} / {num2} = {dividir(num1, num2)}")
            else:
                print("Opción no válida. Intenta de nuevo.")

        except ValueError:
            print("Entrada no válida. Por favor ingresa un número.")

# Llamar a la función calculadora para que empiece a funcionar
calculadora()