# -*- coding: utf-8 -*-
"""Factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZ2808zWomHMIU0pjVtk7Bt01f3Yq4UF
"""

def factorial_iterativo(n):
    if n < 0:
        return "El factorial no está definido para números negativos."
    resultado = 1
    for i in range(1, n + 1):
        resultado *= i
    return resultado

# Solicitar al usuario el número
numero = int(input("Introduce un número para calcular su factorial: "))
print(f"El factorial de {numero} es {factorial_iterativo(numero)}")