# -*- coding: utf-8 -*-
"""Fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuL4xmpHpDZCSGSDBRjxtNjFlfUGooE7
"""

def fibonacci(n):
    # Verificar si el número de términos es válido
    if n <= 0:
        return "Por favor ingresa un número mayor a 0."

    secuencia = []

    a, b = 0, 1
    for _ in range(n):
        secuencia.append(a)
        a, b = b, a + b  # Actualizar los valores de a y b

    return secuencia

# Solicitar al usuario el número de términos
num_terminos = int(input("Introduce el número de términos de la secuencia de Fibonacci: "))
print(f"La secuencia de Fibonacci con {num_terminos} términos es: {fibonacci(num_terminos)}")