# -*- coding: utf-8 -*-
"""Hola Mundo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5WjqVp1UIxgPxGzXq0xu1Hy1sT66vM5
"""

print("Hola Mundo")