# -*- coding: utf-8 -*-
"""Numero Primo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhsOeKLtLgzhJ_-8vS2vRpBf0AOpUGeN
"""

def es_primo(n):
    # Verificar si el número es menor o igual a 1
    if n <= 1:
        return False

    # Verificar divisibilidad por todos los números hasta la raíz cuadrada de n
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

# Solicitar al usuario el número
numero = int(input("Introduce un número para verificar si es primo: "))
if es_primo(numero):
    print(f"{numero} es un número primo.")
else:
    print(f"{numero} no es un número primo.")